let employee = [
  {
    id: 1,
    name: "Brittan",
    email: "bharvett0@mapquest.com",
    gender: "Polygender",
  },
  {
    id: 2,
    name: "Kimbra",
    email: "kletcher1@nationalgeographic.com",
    gender: "Female",
  },
  {
    id: 3,
    name: "Collen",
    email: "clarter2@tripadvisor.com",
    gender: "Female",
  },
  { id: 4, name: "Minnie", email: "mfolomkin3@nymag.com", gender: "Female" },
  { id: 5, name: "Lillis", email: "lgaitung4@admin.ch", gender: "Female" },
  {
    id: 6,
    name: "Scott",
    email: "smatthis5@creativecommons.org",
    gender: "Male",
  },
  {
    id: 7,
    name: "Romy",
    email: "rrawlingson6@delicious.com",
    gender: "Female",
  },
  { id: 8, name: "Tobiah", email: "tslaymaker7@mlb.com", gender: "Male" },
  { id: 9, name: "Gaven", email: "gglasscock8@webeden.co.uk", gender: "Male" },
  {
    id: 10,
    name: "Brandy",
    email: "bmclleese9@businessinsider.com",
    gender: "Male",
  },
  { id: 11, name: "Nichols", email: "npichmanna@google.nl", gender: "Male" },
  { id: 12, name: "Bea", email: "bcanbyb@icio.us", gender: "Female" },
  {
    id: 13,
    name: "Gerianna",
    email: "gzuckerc@marriott.com",
    gender: "Female",
  },
  { id: 14, name: "Terri", email: "ttroppmannd@epa.gov", gender: "Female" },
  { id: 15, name: "Vonnie", email: "velpheye@ft.com", gender: "Female" },
  { id: 16, name: "Hazel", email: "hglazyerf@squarespace.com", gender: "Male" },
  { id: 17, name: "Nicki", email: "nwalesag@is.gd", gender: "Female" },
  {
    id: 18,
    name: "Egan",
    email: "echataignierh@miitbeian.gov.cn",
    gender: "Male",
  },
  { id: 19, name: "Sinclair", email: "smcconneli@unblog.fr", gender: "Male" },
  { id: 20, name: "Gregoor", email: "gabrashkovj@webs.com", gender: "Male" },
  { id: 21, name: "Bordie", email: "bkubuk@va.gov", gender: "Male" },
  { id: 22, name: "Brand", email: "bodeeganl@globo.com", gender: "Male" },
  { id: 23, name: "Twila", email: "tpemberym@clickbank.net", gender: "Female" },
  { id: 24, name: "Lorrin", email: "lmcclancyn@jigsy.com", gender: "Agender" },
  { id: 25, name: "Munroe", email: "mbardayo@aboutads.info", gender: "Male" },
  { id: 26, name: "Tate", email: "tlammertsp@wikispaces.com", gender: "Male" },
  { id: 27, name: "Koo", email: "kborgneq@usgs.gov", gender: "Female" },
  { id: 28, name: "Melisa", email: "mleefer@webmd.com", gender: "Female" },
  { id: 29, name: "Claudia", email: "cwoolmers@naver.com", gender: "Female" },
  { id: 30, name: "Gordy", email: "gwoodberryt@wordpress.org", gender: "Male" },
  { id: 31, name: "Hendrick", email: "hbauldreyu@histats.com", gender: "Male" },
  { id: 32, name: "Jon", email: "jcholmondeleyv@netscape.com", gender: "Male" },
  { id: 33, name: "Shane", email: "ssheltonw@ucsd.edu", gender: "Female" },
  { id: 34, name: "Goran", email: "gswinex@time.com", gender: "Male" },
  { id: 35, name: "Palm", email: "plambricky@jigsy.com", gender: "Male" },
  { id: 36, name: "Avery", email: "acarlettoz@imgur.com", gender: "Male" },
  {
    id: 37,
    name: "Monique",
    email: "mstiddard10@bloglovin.com",
    gender: "Female",
  },
  { id: 38, name: "Lisabeth", email: "liron11@ning.com", gender: "Female" },
  { id: 39, name: "Artie", email: "alardge12@wikimedia.org", gender: "Male" },
  { id: 40, name: "Valma", email: "vwarsop13@github.com", gender: "Female" },
  { id: 41, name: "Cassy", email: "ciston14@mediafire.com", gender: "Female" },
  {
    id: 42,
    name: "Lyndel",
    email: "lmaunton15@hatena.ne.jp",
    gender: "Female",
  },
  { id: 43, name: "Katina", email: "kgarces16@booking.com", gender: "Female" },
  {
    id: 44,
    name: "Lodovico",
    email: "liglesia17@altervista.org",
    gender: "Genderqueer",
  },
  { id: 45, name: "Griffith", email: "gcornish18@de.vu", gender: "Male" },
  { id: 46, name: "Hadrian", email: "hortzen19@tmall.com", gender: "Male" },
  {
    id: 47,
    name: "Kliment",
    email: "khanning1a@people.com.cn",
    gender: "Male",
  },
  { id: 48, name: "Averil", email: "agoodreid1b@cbc.ca", gender: "Male" },
  {
    id: 49,
    name: "Renate",
    email: "rvanderweedenburg1c@sciencedirect.com",
    gender: "Female",
  },
  {
    id: 50,
    name: "Clayson",
    email: "cfiorentino1d@reference.com",
    gender: "Male",
  },
  { id: 51, name: "Fey", email: "fbroader1e@baidu.com", gender: "Female" },
  {
    id: 52,
    name: "Ekaterina",
    email: "esantostefano1f@bloglines.com",
    gender: "Female",
  },
  { id: 53, name: "Marwin", email: "malcoran1g@edublogs.org", gender: "Male" },
  {
    id: 54,
    name: "Cory",
    email: "cleadbeatter1h@shutterfly.com",
    gender: "Female",
  },
  {
    id: 55,
    name: "Meghann",
    email: "msabater1i@unblog.fr",
    gender: "Non-binary",
  },
  {
    id: 56,
    name: "Eden",
    email: "eklausen1j@networkadvertising.org",
    gender: "Female",
  },
  {
    id: 57,
    name: "Sigmund",
    email: "scardall1k@earthlink.net",
    gender: "Male",
  },
  { id: 58, name: "Caria", email: "cboldison1l@reddit.com", gender: "Female" },
  { id: 59, name: "Babette", email: "bladley1m@sfgate.com", gender: "Female" },
  {
    id: 60,
    name: "Tommy",
    email: "twilshere1n@apple.com",
    gender: "Genderqueer",
  },
  { id: 61, name: "Hanni", email: "hhaddleston1o@cnn.com", gender: "Female" },
  { id: 62, name: "Monika", email: "mjohann1p@jigsy.com", gender: "Female" },
  {
    id: 63,
    name: "Allison",
    email: "averrell1q@biblegateway.com",
    gender: "Female",
  },
  {
    id: 64,
    name: "Shandie",
    email: "schant1r@over-blog.com",
    gender: "Female",
  },
  { id: 65, name: "Griffith", email: "gsnibson1s@prlog.org", gender: "Male" },
  {
    id: 66,
    name: "Royce",
    email: "rpesic1t@biglobe.ne.jp",
    gender: "Genderfluid",
  },
  {
    id: 67,
    name: "Darda",
    email: "dandrew1u@networksolutions.com",
    gender: "Female",
  },
  { id: 68, name: "Tirrell", email: "tlamboll1v@paypal.com", gender: "Male" },
  { id: 69, name: "Ginevra", email: "godocherty1w@xrea.com", gender: "Female" },
  {
    id: 70,
    name: "Gavra",
    email: "gsautter1x@elpais.com",
    gender: "Genderqueer",
  },
  {
    id: 71,
    name: "Rosalind",
    email: "rmatonin1y@elegantthemes.com",
    gender: "Genderqueer",
  },
  { id: 72, name: "Tierney", email: "tpudsey1z@smh.com.au", gender: "Female" },
  {
    id: 73,
    name: "Lexi",
    email: "lclempton20@pagesperso-orange.fr",
    gender: "Female",
  },
  {
    id: 74,
    name: "Dinah",
    email: "dcorrin21@yellowpages.com",
    gender: "Female",
  },
  { id: 75, name: "Frankie", email: "fcash22@1und1.de", gender: "Male" },
  { id: 76, name: "Eb", email: "ewarrier23@bigcartel.com", gender: "Male" },
  {
    id: 77,
    name: "Cornelia",
    email: "clyndon24@e-recht24.de",
    gender: "Female",
  },
  { id: 78, name: "Abbot", email: "ahadwick25@cam.ac.uk", gender: "Male" },
  { id: 79, name: "Dotty", email: "drottgers26@prlog.org", gender: "Female" },
  {
    id: 80,
    name: "Norbie",
    email: "nbittleson27@sakura.ne.jp",
    gender: "Non-binary",
  },
  { id: 81, name: "Cary", email: "csouley28@imageshack.us", gender: "Male" },
  { id: 82, name: "Bride", email: "bcockshoot29@flavors.me", gender: "Female" },
  {
    id: 83,
    name: "Ezequiel",
    email: "etoppes2a@technorati.com",
    gender: "Male",
  },
  { id: 84, name: "Norton", email: "noldland2b@sitemeter.com", gender: "Male" },
  {
    id: 85,
    name: "Bertha",
    email: "bwoodwin2c@twitpic.com",
    gender: "Agender",
  },
  {
    id: 86,
    name: "Hermine",
    email: "hconan2d@networkadvertising.org",
    gender: "Female",
  },
  { id: 87, name: "Dinnie", email: "dhold2e@newsvine.com", gender: "Female" },
  { id: 88, name: "Quinlan", email: "qdarinton2f@webmd.com", gender: "Male" },
  { id: 89, name: "Elihu", email: "edeverick2g@about.me", gender: "Male" },
  { id: 90, name: "Sibbie", email: "sfines2h@meetup.com", gender: "Female" },
  {
    id: 91,
    name: "Annelise",
    email: "aguyver2i@thetimes.co.uk",
    gender: "Non-binary",
  },
  { id: 92, name: "Vida", email: "vlethebridge2j@apple.com", gender: "Female" },
  { id: 93, name: "Brett", email: "bjeske2k@intel.com", gender: "Male" },
  {
    id: 94,
    name: "Hermann",
    email: "hreicharz2l@csmonitor.com",
    gender: "Male",
  },
  { id: 95, name: "Julian", email: "jdiver2m@cbsnews.com", gender: "Male" },
  { id: 96, name: "Hadleigh", email: "hblumire2n@nasa.gov", gender: "Male" },
  { id: 97, name: "Gilberta", email: "gdello2o@nytimes.com", gender: "Female" },
  { id: 98, name: "Derrek", email: "dmcgaughie2p@msu.edu", gender: "Male" },
  {
    id: 99,
    name: "Clo",
    email: "clillicrop2q@reference.com",
    gender: "Female",
  },
  { id: 100, name: "Morrie", email: "mweekes2r@google.fr", gender: "Male" },
];

function displayData() {
  let row = "";
  for (emp of employee) {
    row =
      row +
      `<tr>
                  <td>${emp.id}</td>
                  <td>${emp.name}</td>
                  <td>${emp.email}</td>
    
                <tr>`;
  }
  document.getElementById("rajni").innerHTML = row;
}
